"""candidato_historico

Revision ID: 0c177ef0fe74
Revises: 5e8a3494b6df
Create Date: 2026-07-17 01:14:44.900546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0c177ef0fe74'
down_revision: Union[str, None] = '5e8a3494b6df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidatos', sa.Column('historico', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidatos', 'historico')
    # ### end Alembic commands ###
