"""add_explicacao_to_curriculo

Revision ID: 27b36f03d6c0
Revises: c4b7a2d8e1f9
Create Date: 2026-05-12 20:04:16.431233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '27b36f03d6c0'
down_revision: Union[str, None] = 'c4b7a2d8e1f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('curriculos', sa.Column('explicacao', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('curriculos', 'explicacao')
    # ### end Alembic commands ###
