"""initial

Revision ID: 2836c5d9c56c
Revises: 
Create Date: 2026-04-05 19:57:16.979239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector 
# revision identifiers, used by Alembic.
revision: str = '2836c5d9c56c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidatos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('telefone', sa.String(length=30), nullable=True),
    sa.Column('origem', sa.String(length=30), nullable=False),
    sa.Column('fonte', sa.String(length=100), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('logradouro', sa.String(length=255), nullable=True),
    sa.Column('numero', sa.String(length=20), nullable=True),
    sa.Column('complemento', sa.String(length=100), nullable=True),
    sa.Column('bairro', sa.String(length=100), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=2), nullable=True),
    sa.Column('cep', sa.String(length=9), nullable=True),
    sa.Column('formacao', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('papel', sa.Enum('RH', 'GESTOR', 'ADMIN', name='papelusuario'), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('vagas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('requisitos_texto', sa.Text(), nullable=False),
    sa.Column('vetor_vaga', Vector(384), nullable=True),
    sa.Column('ranking_mercado', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('peso_rh', sa.Float(), nullable=False),
    sa.Column('peso_mercado', sa.Float(), nullable=False),
    sa.Column('peso_curriculo', sa.Float(), nullable=False),
    sa.Column('peso_entrevista_rh', sa.Float(), nullable=False),
    sa.Column('peso_entrevista_tec', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidaturas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidato_id', sa.UUID(), nullable=False),
    sa.Column('vaga_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('NOVO', 'AGUARDANDO_PROC', 'PROCESSANDO', 'TRIAGEM_PENDENTE', 'APROVADO_TRIAGEM', 'REPROVADO_TRIAGEM', 'ENTREVISTA_RH_AGENDADA', 'ENTREVISTA_RH_REALIZADA', 'REPROVADO_RH', 'ENTREVISTA_TEC_AGENDADA', 'ENTREVISTA_TEC_REALIZADA', 'REPROVADO_TECNICO', 'DECISAO_PENDENTE', 'CONTRATADO', 'NAO_APROVADO', 'BANCO_TALENTOS', name='statuscandidatura'), nullable=False),
    sa.Column('score_total', sa.Float(), nullable=True),
    sa.Column('historico', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidato_id'], ['candidatos.id'], ),
    sa.ForeignKeyConstraint(['vaga_id'], ['vagas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('curriculos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidato_id', sa.UUID(), nullable=False),
    sa.Column('texto_extraido', sa.Text(), nullable=True),
    sa.Column('vetor_embedding', Vector(384), nullable=True),
    sa.Column('skills_extraidas', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('score_rh', sa.Float(), nullable=True),
    sa.Column('score_mercado', sa.Float(), nullable=True),
    sa.Column('score_curriculo', sa.Float(), nullable=True),
    sa.Column('processado_em', sa.DateTime(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidato_id'], ['candidatos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidato_id')
    )
    op.create_table('entrevistas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidatura_id', sa.UUID(), nullable=False),
    sa.Column('entrevistador_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('score_manual', sa.Float(), nullable=True),
    sa.Column('anotacoes', sa.Text(), nullable=True),
    sa.Column('pontos_fortes', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('pontos_fracos', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('agendada_para', sa.DateTime(), nullable=True),
    sa.Column('realizada_em', sa.DateTime(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidatura_id'], ['candidaturas.id'], ),
    sa.ForeignKeyConstraint(['entrevistador_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entrevistas')
    op.drop_table('curriculos')
    op.drop_table('candidaturas')
    op.drop_table('vagas')
    op.drop_table('usuarios')
    op.drop_table('candidatos')
    # ### end Alembic commands ###
