"""gestores_ids_e_historico_edicoes

Revision ID: 313dfbc4f933
Revises: a6ec7142e850
Create Date: 2026-04-26 23:53:28.267908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '313dfbc4f933'
down_revision: Union[str, None] = 'a6ec7142e850'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entrevistas', sa.Column('historico_edicoes', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('vagas', sa.Column('gestores_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vagas', 'gestores_ids')
    op.drop_column('entrevistas', 'historico_edicoes')
    # ### end Alembic commands ###
