"""vaga_historico

Revision ID: a266a87bd219
Revises: 0c177ef0fe74
Create Date: 2026-07-17 01:50:00.343381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a266a87bd219'
down_revision: Union[str, None] = '0c177ef0fe74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vagas', sa.Column('historico', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vagas', 'historico')
    # ### end Alembic commands ###
