"""curriculo_por_candidatura

Revision ID: a6ec7142e850
Revises: 2ca5f0b6e33e
Create Date: 2026-04-26 17:34:47.200544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6ec7142e850'
down_revision: Union[str, None] = '2ca5f0b6e33e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('curriculos', sa.Column('candidatura_id', sa.UUID(), nullable=False))
    op.drop_constraint('curriculos_candidato_id_key', 'curriculos', type_='unique')
    op.create_unique_constraint(None, 'curriculos', ['candidatura_id'])
    op.drop_constraint('curriculos_candidato_id_fkey', 'curriculos', type_='foreignkey')
    op.create_foreign_key(None, 'curriculos', 'candidaturas', ['candidatura_id'], ['id'])
    op.drop_column('curriculos', 'candidato_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('curriculos', sa.Column('candidato_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'curriculos', type_='foreignkey')
    op.create_foreign_key('curriculos_candidato_id_fkey', 'curriculos', 'candidatos', ['candidato_id'], ['id'])
    op.drop_constraint(None, 'curriculos', type_='unique')
    op.create_unique_constraint('curriculos_candidato_id_key', 'curriculos', ['candidato_id'])
    op.drop_column('curriculos', 'candidatura_id')
    # ### end Alembic commands ###
