"""add_arquivo_pdf_to_curriculo

Revision ID: ccee08033715
Revises: 27b36f03d6c0
Create Date: 2026-05-12 20:59:30.649093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccee08033715'
down_revision: Union[str, None] = '27b36f03d6c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('curriculos', sa.Column('arquivo_pdf', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('curriculos', 'arquivo_pdf')
    # ### end Alembic commands ###
